### ISSUE TITLE
Upload NLPBA corpus to TagTog

### ISSUE THREAD

**Issue by ashishbaghudana** [ashishbaghudana/mthesis-ashish#11]
* ~~[ ] Commit NLPBA in anndoc (tagtog) format in repository~~ (See issue #20)
* [x] For all the entity classes written in the ann.jsons (e_1, e_2, ...), write below a map of their intended class names, as in "Gene", "Protein", ...
* [x] @jmcejuela Have tagtog project (name: relna)
* [ ] with NLPBA documents (500 subset)

**Comment by juanmirocks** [comment]
tagtog project, relna: https://www.tagtog.net/jmcejuela/relna/pool

So far empty until #20 is fixed

**Comment by juanmirocks** [comment]
@ashishbaghudana I assign this task to you since I don't have more to do. How are you doing with the format?

**Comment by ashishbaghudana** [comment]
I'm done annotating about 20 documents.

**Comment by juanmirocks** [comment]
OK, then I close the issue. Upload more documents as you see fit. When you hit the limit of 100 docs, I will make it bigger.
