### ISSUE TITLE
Upload NLBPA corpus to repository

### ISSUE THREAD

**Issue by jmcejuela** [ashishbaghudana/mthesis-ashish#20]
* [x] Move from current location to `/corpora/nlpba/anndoc/`
* [x] Upload original nlpba files to `/orpora/nlpba/iob2/`
* [x] Fill in `annotatable: parts` (with html ids)
* [x] Write here ashish's username: **Ashish**
* [x] Rename .json files to end in `.ann.json`
* [x] Check that the html structure needs several changes. [See sample file](https://github.com/jmcejuela/tagtog-doc/wiki/plain.html%20~%20sample%20file). At least:
  * [x] meta UTF-8 is mandatory
  * [x] `class=anndoc` in html element is mandatory
  * [x] `<div class="content">` to wrap paragraphs is mandatory
* [x] Fix offsets (missing `text`)
* [x] Put README on parent folder and document:
  * [x] why the name "genia4er"
  * [x] How you construct title, abstrac (which is artificial), and one single paragraph
* [x] Prefix the who's with `user:`
* [x] Put html ids within string quotes
* [x] Move header to parent
* [x] Put paragraphs under `<div class="content">`
* [x] Text appears to be wrong. For example:
  * doc `90110496` has in .html "Anti-Ro( SSA) autoantibodies" (seems wrong) and ann.json has "Anti-Ro (SSA) autoantibodies" (seems fine, but it's mandatory that both match)
* [x] Offsets appear to be wrong
  * doc `90110496` the first entity should start in offset-start `0`, not 1
* [x] part (ids) of entities seem to be wrong
  * doc `90110496` You assign all rest entities to partId `s2h1` whereas it should be `s2p1`
* [x] **DO THIS** `grep` any possible weird spaces and if so fix in your entity offset texts or in the html (check for possible wrong `\n` or `\r` or `\r\n` or `\t` (tab))
* [x] See image comment on skype

**Comment by ashishbaghudana** [comment]
@jmcejuela README file is also provided.

**Comment by juanmirocks** [comment]
@ashishbaghudana reopened issue. See new bugs found. Note that I actually only checked with doc `90110496` so please test extensively all other documents for the same type of errors.

Besides that, I myself am essentially done in tagtog to allow uploading anndocs. Let me know when this is fixed.

**Comment by ashishbaghudana** [comment]
Also (not fully sure, but please check) you may have weird spaces in your entity offset texts or in the html (check for possible wrong \n or \r or \r\n or \t (tab))

Could you point out an example? I seem to have fixed everything else.

**Comment by juanmirocks** [comment]
OK, fine, so far I close it.
