### ISSUE TITLE
Annotation Guidelines

### ISSUE THREAD

**Issue by ashishbaghudana** [ashishbaghudana/mthesis-ashish#23]
* [x] First draft of [Annotation Guidelines](https://github.com/ashishbaghudana/mthesis-ashish/wiki/Annotation-Guidelines)
* [ ] Second draft of Annotation Guidelines to contain changes to the JNLPBA corpus along with the original inferred guidelines.
* [ ] List examples of changes, and why the need for the change.

**Comment by ashishbaghudana** [comment]
Annotation in the master document
![Annotation in the master document](https://cloud.githubusercontent.com/assets/3714983/10305957/e11371a0-6c23-11e5-9619-827aefc140be.png)

Modifications in annotation
![Modifications in annotation](https://cloud.githubusercontent.com/assets/3714983/10305965/f2641fa4-6c23-11e5-87ef-7b849249e3d5.png)

**Comment by juanmirocks** [comment]
@ashishbaghudana we can close ?
